repos:
  - repo: https://github.com/go-juno/pre-commit-golang
    rev: v0.0.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      - id: golangci-lint
      - id: go-build
      - id: go-mod-tidy
