// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package cmd

import (
	"github.com/go-juno/juno/api/command"
	"github.com/go-juno/juno/internal/endpoint"
	"github.com/go-juno/juno/internal/service"
	"github.com/go-juno/juno/pkg/cli"
)

// Injectors from wire.go:

// initApp init endpoints
func InitServer() ([]*cli.Command, error) {
	baseEnvService := service.NewBaseEnvService()
	fileService := service.NewFileService()
	modService := service.NewModService()
	endpoints := endpoint.NewEndpoints(baseEnvService, fileService, modService)
	v := command.GenCommandList(endpoints)
	return v, nil
}
