// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package cmd

import (
	"github.com/go-juno/juno/api/command"
	"github.com/go-juno/juno/pkg/cli"
)

// Injectors from wire.go:

// initApp init endpoints
func InitServer() ([]*cli.Command, error) {
	v := command.GenCommandList()
	return v, nil
}
